services:
  whymove-app:
    image: whymove-app:latest
    container_name: whymove-app
    restart: unless-stopped
    ports:
      - "4121:3000"
    env_file:
      - .env
    networks:
      - npm_default

networks:
  npm_default:
    external: true
